[build]
target = "aarch64-none-elf.json"

[target.'cfg(target_os = "none")']
#rustflags = ["-C", "link-args= -Ttext 0xffff800000080000"]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
