[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "x86_64-unknown-uefi"# "aarch64-unknown-uefi"

[dependencies]
bootloader = "0.9.23"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
