[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "target.json"

[dependencies]
bootloader = "0.9.23"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
