#
# Makefile
#

CIRCLEHOME = ../..

OBJS	= main.o kernel.o

LIBS	= $(CIRCLEHOME)/lib/libcircle.a $(CIRCLEHOME)/lib/fonts/libfont.a $(CIRCLEHOME)/lib/rpi/libbcm.a $(CIRCLEHOME)/lib/peripherals/libperi.a

include ../Rules.mk

-include $(DEPS)
