/* generated by bin2h, do not edit */

extern unsigned char binary_boot_bin[512];
extern unsigned char binary_bootboot_bin[13312];
extern unsigned char binary_bootboot_efi[103073];
extern unsigned char binary_bootboot_img[34912];
extern unsigned char binary_bootboot_rv64[8192];
extern unsigned char binary_LICENCE_broadcom[1594];
extern unsigned char binary_bootcode_bin[52456];
extern unsigned char binary_fixup_dat[7297];
extern unsigned char binary_start_elf[2939744];
