/* generated by bin2h, do not edit */

extern unsigned char binary_boot_bin[512];
extern unsigned char binary_bootboot_bin[12288];
extern unsigned char binary_bootboot_efi[100932];
extern unsigned char binary_bootboot_img[34712];
extern unsigned char binary_LICENCE_broadcom[1594];
extern unsigned char binary_bootcode_bin[52480];
extern unsigned char binary_fixup_dat[7289];
extern unsigned char binary_start_elf[2949248];
