#ifndef CONFIG_H
#define CONFIG_H

#define KERNEL 1
#define PRODUCTION 1

#define GLOBAL_MEMSIZE 200000000
#define RECEIVE_PORTAL_QUOTA 100000
#define CREATEDOMAIN_PORTAL_QUOTA 5000
#define NUMBER_DZMEM 20000
#define HEAP_BYTES_INIT (512 * 1024)
#define HEAP_BYTES_DOMAINZERO (2 * 1024 * 1024)
#define CODE_BYTES_DOMAINZERO (4 * 1024 * 1024)
#define CODE_BYTES_DOMAININIT (256 * 1024)
#define MAX_NUMBER_DOMAINS 200
#define ALL_ARRAYS_32BIT
#define INIT_LIB "init2.jll"

#define DIRECT_SEND_PORTAL 1
#define SERVICE_EAGER_CLEANUP 1
#define NOTIFY_SERVICE_CLEANUP 1
#define VISIBLE_PORTALS 1
#define TIMER_HZ 10

#define NOTICE_GC 1
#define GC_USE_NEW 1
#define GC_NEW_IMPL 1
#define GC_CHUNKED_IMPL 1
#define ENABLE_GC 1
#define ROLLFORWARD_ON_GC 1
#define MPROTECT_HEAP 1

#define FASTER_METHOD_LOOKUP 1
#define USE_LIB_INDEX 1
#define FAST_MEMORY_CALLS 1
#define ATOMIC_MEMORY 1
#define MEMORY_USE_ORG 1

#define PROFILE_HEAPUSAGE 1
#define USE_MAGIC 1

#define HEAP_BYTES_OTHER (30 * 1024 * 1024)
#define CODE_BYTES (16 * 40 * 1024)
#define CODE_FRAGMENTS 30
#define HEAP_RESERVE (10 * 1024)

#define STACK_CHUNK      13
#define STACK_GROW       1
#define STACK_CHUNK_SIZE (1 << STACK_CHUNK)

#define MYPARAMS_SIZE 1024

#define MAX_NUMBER_LIBS 100
#define MAX_DEP_INSTANCES 300
#define MAX_REGISTERED 50
#define MAX_SERVICES 1500

#define LL_SCHEDULER      "jx/scheduler/LLRRobin"
#define HL_SCHEDULER_INIT "jx/scheduler/HLRRobin_mini"

#define THREAD_NAME_MAXLEN 40
#define STACK_TRACE_LIMIT 100

#define CPU_MHZ 1000

#endif
